public class CategorySelector {
	
	
	public static List<Category__c> getListOfcatgry(Set<Id> catgryIsSet){
		
		test11;
		test12;
		test13;
		test14;
		test15;
		return null;
	}


    //Query all SH checCategroy list from Opporutnity Id
	public static Map<Id, List<Category__c>> getSHCategoryMapByOppIds(Set<Id> oppIds){
	
	 return null;
	}


	//CUBE section
	public static List<Category__c> getCategoriesForCube(Set<Id> categoryCubeIdSet){
		
		return null;
	}

	public static Map<Id, List<Category__c>> getCubeCategoryMapByOppIds(Set<Id> oppIds){
	
	  return null;
	}

}